# pull the Node.js Docker image
FROM node:alpine

# create the directory inside the container
WORKDIR /usr/src/app

# copy the package.json files from local machine to the workdir in container
COPY package*.json ./

# run npm install in our local machine

# copy the generated modules and all other files to the container
COPY . .
RUN npm update
RUN npm i
RUN npm install dotenv --save
RUN npm i express cors dotenv express-validator
# our app is running on port 5000 within the container, so need to expose it

# the command that starts our app
CMD ["npm", "run", "start"]
